const { zokou } = require("../framework/zokou");
const axios = require("axios");

// --- COMMAND: GITHUB USER INFO ---
zokou({
  'nomCom': 'github',
  'reaction': '🐙',
  'categorie': "Search"
}, async (dest, zk, reponse) => {
  const { ms, arg, prefixe } = reponse;
  const username = arg.join(" ");

  if (!username) {
    return zk.sendMessage(dest, { text: `Please provide a GitHub username.\nExample: ${prefixe}github Fred1e` }, { quoted: ms });
  }

  try {
    const response = await axios.get(`https://api.github.com/users/${username}`);
    const data = response.data;

    let caption = `
   *GITHUB USER INFO*
       
🚩 *ID:* ${data.id}
👤 *Name:* ${data.name || 'Not provided'}
📝 *Username:* ${data.login}
✨ *Bio:* ${data.bio || 'No bio available'}
🏢 *Company:* ${data.company || 'None'}
📍 *Location:* ${data.location || 'Unknown'}
📧 *Email:* ${data.email || 'Private'}
📰 *Blog:* ${data.blog || 'None'}
🔓 *Public Repos:* ${data.public_repos}
🔐 *Public Gists:* ${data.public_gists}
👪 *Followers:* ${data.followers}
🫶 *Following:* ${data.following}
🔗 *Profile Link:* ${data.html_url}

*Generated by Ongito-Md*`;

    await zk.sendMessage(dest, { 
      image: { url: data.avatar_url }, 
      caption: caption 
    }, { quoted: ms });

  } catch (error) {
    zk.sendMessage(dest, { text: "GitHub username not found. Please check the spelling." }, { quoted: ms });
  }
});

// --- COMMAND: GITCLONE (WITH SIZE CHECK) ---
zokou({
  'nomCom': 'gitclone',
  'reaction': '📥',
  'categorie': "Download"
}, async (dest, zk, reponse) => {
  const { ms, arg, prefixe } = reponse;
  const repoUrl = arg.join(" ");

  if (!repoUrl) {
    return zk.sendMessage(dest, { text: `Please provide a GitHub repository link.\nExample: ${prefixe}gitclone https://github.com/mr-X-force/LUCKY-MD-XFORCE` }, { quoted: ms });
  }

  const regex = /(?:https|git)(?::\/\/|@)github\.com[\/:]([^\/]+)\/(.+)/;
  if (!regex.test(repoUrl)) {
    return zk.sendMessage(dest, { text: "That is not a valid GitHub repository link!" }, { quoted: ms });
  }

  try {
    const [, user, repo] = repoUrl.match(regex);
    const repoName = repo.replace(/.git$/, "");
    const apiUrl = `https://api.github.com/repos/${user}/${repoName}`;
    
    const response = await axios.get(apiUrl);
    const data = response.data;

    // 100MB Limit (102,400 KB)
    const maxSizeKB = 102400; 

    if (data.size > maxSizeKB) {
      return zk.sendMessage(dest, { 
        text: `❌ *Repository is too large!*\n\nSize: ${(data.size / 1024).toFixed(2)} MB\nOur limit is: 100 MB.\n\nPlease download it manually here: ${data.html_url}` 
      }, { quoted: ms });
    }

    const downloadUrl = `https://github.com/${user}/${repoName}/archive/refs/heads/${data.default_branch}.zip`;

    let caption = `
*GIT CLONE DOWNLOAD*

📂 *Name:* ${data.name}
👤 *Owner:* ${data.owner.login}
📦 *Size:* ${(data.size / 1024).toFixed(2)} MB
⭐ *Stars:* ${data.stargazers_count}
🌐 *Branch:* ${data.default_branch}

_Processing your request... The ZIP file will be sent shortly._`;

    await zk.sendMessage(dest, { text: caption }, { quoted: ms });

    await zk.sendMessage(dest, { 
      document: { url: downloadUrl }, 
      fileName: `${repoName}.zip`, 
      mimetype: "application/zip" 
    }, { quoted: ms });

  } catch (error) {
    zk.sendMessage(dest, { text: "Failed to fetch repository. Ensure it is public and the link is correct." }, { quoted: ms });
  }
});
